name = input("Enter your name: ")
age = input("Enter your age: ")
house_number = input("Enter your house number: ")
street_name = input("Enter your street name: ")
print("This is " + name + " he is " + age + " years old and lives at house number " + house_number + " on " + street_name)